Nexmo/nexmo-cli

README.md

Just added a link to node packages and that you need to do npm install as root/sudo

Improved install instructions

---

README.md

Fixes typos in the sample output

CLI output example typo fix

---

src/bin.js
src/blocked-io.js

Fixes #13. Code provided via https://github.com/tj/commander.js/issues/530#issuecomment-222362654

Enforce blocked IO

---

src/request.js
tests/request.js

Also renamed all mentions of `misdn` to `number` as the rest of the CLI does. Closes #41.

Accept plus sign in number

---

package.json
src/client.js
tests/client.js
tests/request.js

Updating the version of the underlying `nexmo-node` package dependency.

nexmo-node 1.0.0 beta5 dependency update

---

package.json

Use fix from newly published `nexmo` library

Use nexmo v1.0.0-beta-7 + bump version

---

README.md

Updated README to show true output of  `number:list --verbose`

Update number:list --verbose output

---

README.md

Add additional clarification to the installation section.

Clarify the Installation instructions

---

package.json
src/bin.js
src/request.js
tests/client.js

Adds Number Insights Advanced call. Awaiting merger of nexmo/nexmo-node#66. 
Also:
* Fixed bug in testing debug mode on node lib

Add Number Insights Advanced call

---

src/response.js
tests/response.js

The latest beta introduced an issue where the credentials were not read out properly. This fixes this.

Fix bug in reading account details

---

MAINTAINING.md

Added some notes for maintainers to explain how new releases are to be drafted.

Add notes for maintainers

---

package.json

Closes #118 by updating the Node library to 1.1.2.

Bump to 0.3.2 - Update Node library

---

README.md
src/bin.js
src/request.js
src/response.js
tests/request.js
tests/response.js

Closes #91 
Add `nexmo app:numbers [app_id]` command to quickly look up numbers for an app.

Add app:numbers command

---

README.md
src/bin.js

Remove --app_id flag from jwt:generate

---

CHANGELOG.md
package.json
src/emitter.js
tests/emitter.js

Closes #108 
Closes #132 
Closes #131

Bump to 0.3.6 - nexmo-node 2.0.2

---

package.json
src/bin.js

Update default page size and index

---

src/bin.js
src/request.js
tests/request.js

Number list search with pattern

---

.eslintrc.js
package.json
src/bin.js
src/client.js
src/config.js
src/request.js
src/response.js
tests/client.js
tests/request.js
tests/response.js

conversation:create
user:create
member:add
mamber:list

adding commands for conversations

---

.npmignore
package-lock.json
package.json
src/request.js

updating jwt generation to parse acl & exp

---

README.md

This PR is basically adding a Snyk badge to the readme, which reflects if there are any vulnerabilities in the existing manifest file (package.json). I think this is a quick win that allows us developers to have confidence on the library we are using.
The vulnerability scanning is free for all public repository, so why not :)
Not really, but perhaps Nexmo might want to sign up with Snyk to scan for other projects (and other languages)
Thanks for allow us to contribute!

PR - Update Readme with Snyk badge

---

README.md

This was a little less than standardized, figured I'd make this PR while reading up on the project.

Capitalize initialisms

---

README.md

It's hard to work out what to do when generating a JWT for voice. So i've added a specific example. Also put in the usage from the help so it's clear that claims are name=value pairs

Add better examples for voice JWT

---

.travis.yml

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
Thanks for contributing to the Nexmo CLI!

remove node 6 from tests

---

package.json

Use `prepublishOnly` instead of deprecated `prepublish`

---

package-lock.json
package.json
src/response.js
tests/response.js

Before: nexmo app:create name
After: nexmo app:create "name"

escape application name in recreate commands

---

package-lock.json
src/client.js

Modified the error message that states:
> Could not initialize Nexmo library. Please run 'nexmo setup' to setup the CLI correctly.
To read:
> Could not initialize Nexmo library. Please run 'nexmo setup <api_key> <api_secret>' to setup the CLI correctly.
Also, updated npm packages to remove dependencies on library versions with critical or high security issues.

Adding <api_key> <api_secret> to nexmo setup error msg. Closes #209

---

package-lock.json
package.json
src/bin.js

Suggest matching commands if the user makes a typo.
N/A

feat(chore): suggest matching commands

---

package-lock.json
package.json
src/bin.js

[didYouMean.js](https://www.npmjs.com/package/didyoumean) is not maintained anymore. It is better to migrate to [leven](https://www.npmjs.com/package/leven).

chore: migrate to leven
