- package.json
Has a beta dependency which is subject to API changes. Thus, be strict about the version of that dependency which the CLI references.
> Be strict about a specific beta dependency

- src/request.js
- tests/request.js
Seems a little bug slipped in when we changed the nexmo module.
> Fix number buying by uing NI Basic instead of advanced

- README.md
- src/response.js
- tests/response.js
Now by default the `balance` command returns a rounded number and reflect the official Nexmo Dashboard. By using the `--verbose` flag one can get the rounded value.
Closes #47
> Set balance precision to match dashboard

- src/validator.js
- tests/validator.js
Closes #43 
Checks if a `status` is present in the response and if it is non-0 it emmits an error.
> Add validation for status

- package.json
VAPI 2-beta2 has been released. This means that the underlying `nexmo` library has been updated. This pull request updates the library that is used so that `nexmo-cli` can be used with VAPI 2-beta2.
> Use 1.0.0-beta6 of nexmo. Bump version.

- src/bin.js
Add aliases for most app commands so that both `app:*` and `apps:*` work.
Two exceptions are `app` and `apps` which still map to `app:show` and `apps:list`.
Closes #75
> Alias app to apps and vice versa

- README.md
- src/emitter.js
- src/request.js
- src/response.js
- tests/request.js
- tests/response.js
Added a feature to the `number:list`, `number:search` and `application:list` commands where it now adds some extra details about the page and total number of items:
```sh
> next number:list -v
Item 1-10 of 11
msisdn       | country | type       | features  | voiceCallbackType | voiceCallbackValue | moHttpUrl | voiceStatusCallbackUrl
-----------------------------------------------------------------------------------------------------------------------------
447555555550 | GB      | landline   | VOICE,SMS | undefined         | undefined          | undefined | undefined             
447555555551 | GB      | landline   | VOICE,SMS | undefined         | undefined          | undefined | undefined             
447555555552 | GB      | landline   | VOICE,SMS | undefined         | undefined …
```
> Add pagination details every table

- README.md
- src/bin.js
- src/request.js
- src/response.js
- tests/request.js
- tests/response.js
Adds sending of an SMS. Only implements the basics to keep things simple. It auto detects if a `from` sender has been given and if not uses `Nexmo CLI` as the from field.
```
> nexmo sms <destination_number> "Hello world!" --confirm
Message sent to:   <destination_number>
Remaining balance: 26.80110000 EUR
Message price:     0.03330000 EUR
> nexmo sms <from_name_or_number> <destination_number> "Hello world!" --confirm
Message sent to:   <destination_number>
Remaining balance: 26.80110000 EUR
Message price:     0.03330000 EUR
```
Closes #17
> Add SMS sending

- src/response.js
- tests/response.js
Closes #57.
Updated `price:country` to determine the max price for a country and return that in the non verbose output. This prevents false advertising and gives people a better expectation of cost.
> Return the max price for a country in the non verbose call

- README.md
- src/client.js
- src/request.js
- src/response.js
- tests/client.js
- tests/request.js
- tests/response.js
Closes #8 
The CLI now first makes an API call before trying to save your credentials, to ensure your credentials are correct.
```sh
> nexmo setup 123 345
Credentials written to /Users/cbetta/.nexmorc
> nexmo setup 123 ABC    
authentication failed
```
> Add account verification on setup

- README.md
- src/request.js
- src/response.js
- tests/response.js
Closes #62 
Shows the number in the output for the `number:buy` and `number:cancel` methods.
```sh
$ nexmo number:buy 441143597860 --confirm
Number purchased: 441143597860
$ nexmo number:cancel 441143597860 --confirm
Number cancelled: 441143597860
$ nexmo nb GB 447* --confirm
Number purchased: 441143597860
```
> Show number in number:buy and number:cancel output

- README.md
- src/bin.js
- src/request.js
- src/response.js
- tests/request.js
- tests/response.js
Closes #63 
I was getting tired of looking up my API credentials on the dashboard or by `cat`-ing my `.nexmorc` file, so I just added a simple way to inspect my credentials as follows:
```sh
$ nexmo account
API Key:    abc123
API Secret: def345
```
Besides me scratching an itch here it is also useful for those of us using the `nexmo-cli` with local credentials (a local `.nexmorc` file). It allows you to quickly confirm what credentials you are using.
> Add account info command

- src/bin.js
- src/request.js
- tests/request.js
This change makes it easier to buy a number quickly and also simplifies the underlying `numberBuy` code.
Usage is now:
```bash
number:buy [number_pattern]
```
If number_pattern is a full number that number will be purchased.
If it’s not a full number and a `--country_id` option is set then a search is performed using `number_pattern` as the pattern.
```bash
number:buy 5 --country_id GB
```
Or, just by the first number for a country:
```bash
number:buy --country_id US
```
`numbers:buy` (plural) has been removed. It threw an exception anyway.
> Simplify number:buy and alias numbers:buy

- README.md
the `--from` parameter should be provided in some cases. Adding a note to the README to highlight this.
> Adding clarification where sms --from is required

- src/config.js
- src/request.js
- tests/request.js
Now throws a nice simple warning instead:
```
Could not read credentials. Please run 'nexmo setup' to setup the CLI. (ENOENT: no such file or directory, open '/Users/cbetta/.nexmorc')
```
> Prevent error when using 'nexmo account' when not authenticated

- src/request.js
We changed the `nexmo` lib to require a level of `advancedSync` for synchronous requests.
> Fix number insight advanced to use right API method

- src/bin.js
Change the output in --help for jwt:generate to suggest `sub` instead of `subject` in order to align with the docs and API
> Changed the help output

- src/request.js
- tests/request.js
The applicationsList API endpoint requires `page_size` instead of `size` to change the pagination window.
Closes #102
> Use page_size instead of size for paginating applications

- src/validator.js
Recent changes in the Node library have caused not all errors to be processed correctly. See nexmo/nexmo-node#78 . While this is being fixed we need to patch the CLI to process this correctly.
Closes #104
> Improve error catching to match changes in Node library

- src/bin.js
- src/request.js
- tests/request.js
Closes #84.
When the `country_code` is provided it will skip the Number Insight lookup for the number and just use the country code as specified.
This affects `number:buy`, `number:cancel` and all `link:*` and `unlink:*` commands.
As a result, long dutch numbers can now be bought, cancelled, updated, assuming the `country_code` flag is provided.
> Update to use country code if provided

- src/request.js
- tests/request.js
Closes #51 
Closes #122 
Sets page size for number list, number search, and application list to 100, to make pagination easier.
> Set page size param to default to the max page size

- CHANGELOG.md
- README.md
- package.json
- src/bin.js
- src/request.js
- src/response.js
- tests/request.js
- tests/response.js
* Update methods that required Number Insight checks to operate to accept a static `country_code` flag
* Change default pagination size for most calls to 100
* Add `app:numbers` command to look up numbers for an application
* Remove `--app_id` flag from `jwt:generate`
Closes #120 
Closes #51 
Closes #84
> Bump to 0.3.3

- package.json
- src/validator.js
Closes #138 
Updates Node library to 2.0.1. Updates error catching to expect new `error.body` object.
> Bump to nexmo-node 2.0.1

- src/bin.js
Change to numbers:update
number:update was being registered twice as a command so when you executed the command it was resulting in the underlying code being executed twice.
This changes one of the registered commands from `number:update` to the plural, `numbers:update`.
> Remove singular number:update duplication

- tests/config.js
Due to difference in newline character in windows config write test was failing. So, this PR just replaces `\r\n` with `\n`
> fixes test for windows

- src/bin.js
This PR aims to address https://github.com/Nexmo/nexmo-cli/issues/136 by updating the description for `number:update` and `numbers:update` so they're no longer identical to the description for `link:app`.
N/A
Thanks for contributing to the Nexmo CLI!
> Updating number:update description to remove ambiguity.

- .gitattributes
- .travis.yml
- tests/config.js
As of 11 October 2018, Travis CI now supports Windows build environment. In light of #177 this PR enables multiple OS build environments (Linux, Windows, and MacOS).
The Windows build currently fails because #177 has not yet been applied. Once that PR is merged, the Windows builds should complete successfully.
> Make TravisCI Run Tests on Multiple Operating Systems

- src/bin.js
moved `numbers:buy` into a separate command so the alias is not overwritten by `nb`.
This doesn't seem very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) though and I'm not quite sure how to make sure this doesn't happen since commander silently overwrites the alias. Subclass it? 
What would be the preferred way to handle this? 
partially handles #141 
Thanks for contributing to the Nexmo CLI!
> [WIP] split aliases into duplicate commands

- .eslintrc.js
- tests/.eslintrc.js
So that mocha globals are only permitted within test code, and not source code.
> Split .eslintrc.js into two

- README.md
- src/bin.js
- src/request.js
- tests/request.js
Fixes #159: Remove vxml
With the shutdown of the call API, the `link:vxml` and `unlink:vxml` commands can be removed as they are no longer used.
Note that this information might be referenced in other areas, ie. the verbose numbers list screen, but this is OK as users may want to see that a number is still linked to vxml in order to identify changes.
> Remove vxml cli commands

- package-lock.json
- src/request.js
- src/response.js
- tests/request.js
- tests/response.js
Implements partial app_id matching for `nexmo app:numbers` to solve #168 
I wasn't entirely sure how to fit the 2 API calls (one to applicationsList, the other to applicationNumbers) in the existing pattern. I feel like this is the most appropriate way out of the options I was thinking of at the time.
Code reviews/suggestions welcome :+1:
> adding partial app id match for 'nexmo an' #168

- README.md
There was a grammatical mistake in **Cancelling a number** section. 
> 
It said
`This is operation can not be reversed`
Changed it to
`This operation can not be reversed`
> Update README.md (grammatical mistake)

- README.md
There was a grammatical mistake in **Delete an application** section
It said
`This is operation can not be reversed`
`This operation can not be reversed`
> Grammatical type error

- src/bin.js
Use consistent grammar for Help printouts
Currently - this thie printout:
```
insight:basic|ib <number>                                         Get details about this number
insight:standard|is [options] <number>                            Get more details about this number like the current carrier. This operation will incur a fee.
insight:advanced|ia [options] <number>                            Get more details about this number like the roaming status and current country of the phone. This operation will incur a fee.
price:sms|ps <number>                                             Gives you the cost of sending an outbound text to a number.
price:voice|pv <number>                                           Gives you the cost of making an outbound call to a number.
price:country|pc …
```
> Use consistent grammar for Help printouts

- README.md
- src/bin.js
- src/request.js
- src/response.js
- tests/response.js
Tries to partly address #223. Added missing alias in `README.md` for the `account` command. The API key and secret can be reported separately using `nexmo account:key` and `nexmo account:secret` with the contributions in this PR. Added test cases to handle the new commands.
> Added commands to gracefully report account information

- package-lock.json
- tests/response.js
We have build failures on the master branch where even though a PR built successfully, `npm run coverage` fails. I can also replicate this locally.
So far, this PR includes an update to caniuse-lite since that also outputs errors, but that didn't fix the overall coverage problem.
> Fixing the Build Failure for Coverage
